# Generated by Django 3.2.13 on 2022-06-11 16:40

import json
from datetime import (
    date,
    timedelta
)

from django.db import migrations
from django.conf import settings
from django.contrib.gis.geos import fromstr


DATA_FILENAME = 'data.json'


def load_data(apps, schema_editor):
    Pin = apps.get_model('pins', 'Pin')
    jsonfile = settings.BASE_DIR / DATA_FILENAME

    with open(str(jsonfile)) as datafile:
        objects = json.load(datafile)

        for obj in objects['elements']:
            try:
                objType = obj['type']

                if objType == 'node':
                    tags = obj['tags']
                    name = tags.get('name', 'no-name')
                    longitude = obj.get('lon', 0)
                    latitude = obj.get('lat', 0)
                    location = fromstr(
                        f'POINT({longitude} {latitude})',
                        srid=4326
                    )

                    tomorrow = date.today() + timedelta(days=1)

                    Pin.objects.create(
                        name=name,
                        location=location,
                        expiration_date=tomorrow
                    )
            except KeyError:
                pass


class Migration(migrations.Migration):

    dependencies = [
        ('pins', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_data)
    ]
